version: '3.7'

services:
  app:
    image: rdeleo/centos7-php7.4-apache-dev:7.4.5
    volumes:
      - ./fixtures/httpdocs:/var/www/html
    ports:
      - "${APP_HTTP_PORT}:80"
    env_file:
      - .env