version: '3.7'

services:
  app:
    image: rdeleo/debian10-php7.3-apache-prod:7.3.17
    volumes:
      - ./fixtures/httpdocs:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env