version: '3.7'

services:
  app:
    image: rdeleo/centos7-php7.2-apache-dev:7.2.27
    volumes:
      - ./fixtures/httpdocs:/var/www/html
    ports:
      - "${APP_HTTP_PORT}:80"
    env_file:
      - .env