version: '3.7'

services:
  app:
    image: rdeleo/centos7-php7.4-apache-prod:7.4.7
    volumes:
      - ./fixtures/httpdocs:/var/www/html
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env